api-version: '1.13'
depend: [
  ]
author: wysohn
permissions:
  tradegui:
    description: root permission
name: TradeGUI
main: io.github.wysohn.tradegui.main.TradeGUI
softdepend:
  - RapidFramework
  - Vault
  - PlaceholderAPI
  - ProtocolLib
  - WorldGuard
  - SmartInvs
  - ScoreboardScreen
  - Citizens
  - GemsEconomy
version: 2.0.0
commands:
  tradegui:
    aliases:
      - tra
      - trade
    description: description
authors: [
]
